### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by pedromjg** [jhermsmeier/git-branch-select#12]
When running: git branch-select

`
/usr/local/lib/node_modules/git-branch-select/node_modules/prompts/dist/index.js:11
  var _ref = _asyncToGenerator(function* (questions = [], { onSubmit = noop, onCancel = noop } = {}) {
                                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-branch-select/node_modules/prompts/index.js:3:7)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
'

**Comment by jhermsmeier** [comment]
Which version of Node are you running this under?

**Comment by jhermsmeier** [comment]
And which version of this package?
